name: Build & Deploy (manually)

on:
  workflow_dispatch:
    inputs:
    
      branch:
        description: 'Branch to (re)deploy from'
        required: true
        default: 'development'
        type: choice
        options:
          - main
          - development

      environment:
        description: 'Environment to (re)deploy to'
        type: environment
        default: 'development'
        required: true

jobs:

  build_frontend:

    name: build frontend
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          branch: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
                
      - name: Install npm packages
        run: |
          cd frontend
          npm install
          
      - name: Build & bundle
        run: |
          cd frontend          
          unset CI # ignore React warnings
          npm run build
          
  build_backend:

    name: build backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          branch: ${{ inputs.branch }}
        
      - name: Fetch submodules
        run: |
          cd backend
          cd apps
          git submodule update --init --recursive
          git submodule update --remote
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Create venv
        run: |
          cd backend
          python3.11 -m venv venv
          
      - name: Install packages
        run: |
          cd backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ifcopenshell # TEMP workaround
          
      - name: Check Django config
        run: |
          cd backend
          source venv/bin/activate
          python3 manage.py check
          
      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate
          python3 manage.py test
          
  deploy_dev:
    
    if: ${{ inputs.environment == 'development' }}
    name: deploy to server (dev)
    needs: [build_frontend, build_backend]
    runs-on: ubuntu-latest
    environment:
      name: development
     
    steps:
      - name: Set up SSH key        
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  
      - name: Install sshpass
        run: sudo apt-get install sshpass
        
      - name: Stop Docker containers
        run: |
          sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} bash <<'ENDSSH'
          cd ${{ vars.REPO_CLONE_PATH }}
          sudo make stop
          ENDSSH
          
      - name: Fetch sources & submodules
        run: |
          sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} bash <<'ENDSSH'
          cd ${{ vars.REPO_CLONE_PATH }}
          git checkout -q ${{ inputs.branch }} && git pull
          sudo make fetch-modules
          cd ${{ vars.REPO_CLONE_PATH }}/backend/apps/ifc_validation/checks/ifc_gherkin_rules && git checkout -q ${{ inputs.branch }} && git pull
          cd ./ifc_validation_models && git checkout -q ${{ inputs.branch }} && git pull
          cd ${{ vars.REPO_CLONE_PATH }}/backend/apps/ifc_validation/checks/step_file_parser && git checkout -q master && git pull
          cd ${{ vars.REPO_CLONE_PATH }}/backend/apps/ifc_validation_models && git checkout -q ${{ inputs.branch }} && git pull
          cd ${{ vars.REPO_CLONE_PATH }}
          ./check-submodules.sh
          ENDSSH
      
      - name: Set VERSION
        run: |
          sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} bash <<'ENDSSH'
          cd ${{ vars.REPO_CLONE_PATH }}
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION="${{ vars.VERSION }}"
          echo "Set VERSION to ${VERSION}"
          echo "Commit hash ${COMMIT_HASH}"
          echo "${VERSION}" > .VERSION          
          ENDSSH
          
      - name: Build Docker images
        run: |
          sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} bash <<'ENDSSH'
          cd ${{ vars.REPO_CLONE_PATH }}
          sudo make rebuild
          ENDSSH
          
      - name: Start Docker containers
        run: |
          sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} bash <<'ENDSSH'
          cd ${{ vars.REPO_CLONE_PATH }}
          sudo docker compose -f ${{ vars.DOCKER_COMPOSE_FILE }} --env-file ${{ vars.ENV_FILE }} up -d
          ENDSSH
