name: CI Build

concurrency: 
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  build_frontend:

    name: build frontend
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
                
      - name: Install npm packages
        run: |
          cd frontend
          npm install

      - name: Build & bundle
        run: |
          cd frontend          
          unset CI # ignore React warnings
          npm run build

  build_backend:

    name: build backend
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fetch submodules
        run: |
          cd backend
          cd apps
          git submodule update --init --recursive
          git submodule update --remote

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Create venv
        run: |
          cd backend
          python3.11 -m venv venv

      - name: Install packages
        run: |
          cd backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ifcopenshell # TEMP workaround

      - name: Check Django config
        run: |
          cd backend
          source venv/bin/activate
          python3 manage.py check

      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate
          python3 manage.py test      
