name: Connect & Check Deployment (manually, no redeploy)

on:
  workflow_dispatch:
    inputs:
    
      environment:
        description: 'Environment to check'
        type: environment
        default: 'development'
        required: true

jobs:

  check:
    
    name: check (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
     
    steps:

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/host.key
          chmod 600 ~/.ssh/host.key
          cat >>~/.ssh/config <<END
          Host host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/host.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check local changes
        run: |
           ssh host 'cd ${{ vars.REPO_CLONE_PATH }} && \
           if [ -z "$(git status --porcelain)" ]; then 
             echo "No local changes"
           else
             echo "ERROR: There are local changes in ${{ inputs.environment }}"
             git status --porcelain
             exit -1
           fi'

      - name: Show repo & git status
        run: |
          ssh host 'cd ${{ vars.REPO_CLONE_PATH }} && \
          echo "*** Validate repository" && \
          git remote get-url origin && git rev-parse --abbrev-ref HEAD && git rev-parse --short HEAD && \
          echo "*** git status" && \
          git status'

      - name: Show submodule status
        run: |
          ssh host 'cd ${{ vars.REPO_CLONE_PATH }} && \
          ./check-submodules.sh'
