name: Connect & Check Deployment (manually, no redeploy)

on:
  workflow_dispatch:
    inputs:
    
      environment:
        description: 'Environment to check'
        type: environment
        default: 'development'
        required: true

jobs:

  # note: duplicate deploy tasks per environment (else unable to access environment secrets)
  deploy_dev:
    
    if: ${{ inputs.environment == 'development' }}
    name: check (dev)
    runs-on: ubuntu-latest
    environment:
      name: development
     
    steps:

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check local changes
        run: |
           ssh dev 'cd ${{ vars.REPO_CLONE_PATH }} && \
           if [ -z "$(git status --porcelain)" ]; then 
             echo "No local changes"
           else
             echo "ERROR: There are local changes"
             git status --porcelain
             exit -1
           fi'

      - name: Show repo & git status
        run: |
          ssh dev 'cd ${{ vars.REPO_CLONE_PATH }} && \
          echo "*** Validate repository" && \
          git remote get-url origin && git rev-parse --abbrev-ref HEAD && git rev-parse --short HEAD && \
          echo "*** git status" && \
          git status'

      - name: Show submodule status
        run: |
          ssh dev 'cd ${{ vars.REPO_CLONE_PATH }} && \
          ./check-submodules.sh'

  # note: duplicate deploy tasks per environment (else unable to access environment secrets)
  deploy_prod:
    
    if: ${{ inputs.environment == 'production' }}
    name: check (prd)
    runs-on: ubuntu-latest
    environment:
      name: production
     
    steps:

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check local changes
        run: |
           ssh prod 'cd ${{ vars.REPO_CLONE_PATH }} && \
           if [ -z "$(git status --porcelain)" ]; then 
             echo "No local changes"
           else
             echo "ERROR: There are local changes"
             git status --porcelain
             exit -1
           fi'

      - name: Show repo & git status
        run: |
          ssh prod 'cd ${{ vars.REPO_CLONE_PATH }} && \
          echo "*** Validate repository" && \
          git remote get-url origin && git rev-parse --abbrev-ref HEAD && git rev-parse --short HEAD && \
          echo "*** git status" && \
          git status'

      - name: Show submodule status
        run: |
          ssh prod 'cd ${{ vars.REPO_CLONE_PATH }} && \
          ./check-submodules.sh'
