name: Dispatch
  
on: repository_dispatch
  
jobs:

  on_dispatch:
    name: On Dispatch
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'development' }}
    
    steps:
      - name: Log received event
        run: ${{ tojson(github.event) }}
        shell: cat {0}

      - name: Dispatch from ifc-gherkin-rules (development)
        run: echo "ifc-gherkin-rules (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-gherkin-rules' && github.event.client_payload.branch == 'development' }}
        
      - name: Dispatch from ifc-validation-data-model (development)
        run: echo "ifc-validation-data-model (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-validation-data-model' && github.event.client_payload.branch == 'development' }}

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: development # branch of Validate repo
          submodules: 'true'

      - name: Show submodule status
        run: |
          cd ${{ github.workspace }}
          ./check-submodules.sh

      - name: Fetch latest submodule 1
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation/checks/ifc_gherkin_rules 
          git fetch
          git checkout -B ${{ github.event.client_payload.branch }} 

      - name: Fetch latest submodule 2
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation_models
          git fetch
          git checkout -B ${{ github.event.client_payload.branch }}
          
      - name: Show submodule status
        run: |
          cd ${{ github.workspace }}
          ./check-submodules.sh

      - name: Commit changes (if any)
        run: |
          cd ${{ github.workspace }}
          git add backend/apps/ifc_validation/checks/ifc_gherkin_rules
          git add backend/apps/ifc_validation_models

      - name: Show git status
        run: |
          cd ${{ github.workspace }}
          git status
