name: Dispatch
  
on: repository_dispatch
  
jobs:

  on_dispatch:
    name: On Dispatch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Log received event
        run: ${{ tojson(github.event) }}
        shell: cat {0}

      - name: Dispatch from ifc-gherkin-rules (development)
        run: echo "ifc-gherkin-rules (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-gherkin-rules' && github.event.client_payload.branch == 'development' }}
        
      - name: Dispatch from ifc-gherkin-rules (main)
        run: echo "ifc-gherkin-rules (main branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-gherkin-rules' && github.event.client_payload.branch == 'main' }}

      - name: Dispatch from ifc-validation-data-model (development)
        run: echo "ifc-validation-data-model (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-validation-data-model' && github.event.client_payload.branch == 'development' }}

      - name: Dispatch from ifc-validation-data-model (main)
        run: echo "ifc-validation-data-model (main branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-validation-data-model' && github.event.client_payload.branch == 'main' }}
