name: Dispatch
  
on: repository_dispatch
  
jobs:

  on_dispatch:
    name: On Dispatch
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'development' }}
    
    steps:
      - name: Log received event
        run: ${{ tojson(github.event) }}
        shell: cat {0}

      - name: Dispatch from ifc-gherkin-rules (development)
        run: echo "ifc-gherkin-rules (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-gherkin-rules' && github.event.client_payload.branch == 'development' }}
        
      - name: Dispatch from ifc-validation-data-model (development)
        run: echo "ifc-validation-data-model (development branch)"
        if: ${{ github.event.client_payload.repo == 'ifc-validation-data-model' && github.event.client_payload.branch == 'development' }}

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: development # branch of Validate repo
          submodules: 'true'

      # - name: Checkout sources & submodules
      #  run: |
      #    cd ${{ github.workspace }}
      #    git clone https://github.com/rw-bsi/validate .
      #    git fetch
      #    git checkout -q --track origin/development
      #    git submodule update --init --recursive
      #    git submodule update --remote

      - name: Fetch latest submodule 1
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation/checks/ifc_gherkin_rules 
          git checkout -q --track origin/${{ github.event.client_payload.branch }} 

      - name: Fetch latest submodule 2
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation/checks/ifc_gherkin_rules/ifc_validation_models 
          git checkout -q --track origin/${{ github.event.client_payload.branch }} 

      - name: Fetch latest submodule 3
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation/checks/step_file_parser 
          git checkout -B master

      - name: Fetch latest submodule 4
        run: |
          cd ${{ github.workspace }}/backend/apps/ifc_validation_models
          git checkout -q --track origin/${{ github.event.client_payload.branch }}
          
      - name: Show submodule status
        run: |
          cd ${{ github.workspace }}
          git submodule foreach --recursive "git remote get-url origin && git rev-parse --abbrev-ref HEAD && git rev-parse --short HEAD && echo $''"

      - name: Show repo status
        run: |
          cd ${{ github.workspace }}
          echo "Validate repository"
          git remote get-url origin && git rev-parse --abbrev-ref HEAD && git rev-parse --short HEAD

      - name: Add changes (if any)
        run: |
          cd ${{ github.workspace }}
          git add backend/apps/ifc_validation/checks/ifc_gherkin_rules
          git add backend/apps/ifc_validation/checks/step_file_parser
          git add backend/apps/ifc_validation_models

      - name: Commit changes (if any)
        run: |
          cd ${{ github.workspace }}
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update of submodules (bSI-Bot via GH action)"
          git push origin development

      - name: Show git status
        run: |
          cd ${{ github.workspace }}
          git status
