name: Build & Deploy

concurrency: 
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://validate.buildingsmart.org
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@v1.0.3
        env:
          FOO: "FOO_VALUE"
          BAR: "BAR_VALUE"
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: FOO,BAR,SHA
          script_stop: true
          script: |
            whoami
            echo "I am $FOO"
            echo "I am $BAR"
            echo "sha: $SHA"  
